number1 = input("Please type an integer and press enter: ")
number2 = input("Please type another integer and press enter: ")
number1 = int(number1)
number2 = int(number2)
print(f"{number1} + {number2} = {number1 + number2}")
